version: "3"
services: 
  trebek-app:
    container_name: "trebek-app"
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "443:443"
  trebek-api:
    restart: always
    container_name: trebek-api
    build: ./api
    volumes:
      - ./api:/usr/apps/trebek-api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
